from typing import Optional
from ._events import Event, Output

class CommandError(RuntimeError): ...

class _CancellationToken:
    # Create an independent cancellation signal.
    def __init__(self) -> None: ...
    # Request cancellation of attached commands.
    def cancel(self) -> None: ...
    # Inspect cancellation state.
    def is_cancelled(self) -> bool: ...

class _Client:
    # Validate explicit connection settings.
    def __init__(self, port: str, user: str, client: str, cwd: str, charset: str) -> None: ...
    # Create an owned command builder.
    def command(self, name: str) -> _Command: ...

class _Command:
    # Append arguments to a new builder.
    def args(self, args: list[str]) -> _Command: ...
    # Supply form input to a new builder.
    def input(self, form: str) -> _Command: ...
    # Set the command deadline in seconds.
    def timeout(self, seconds: float) -> _Command: ...
    # Attach a shared cancellation signal.
    def cancellation(self, token: _CancellationToken) -> _Command: ...
    # Configure the existing Rust reconcile engine.
    def reconcile(self, metadata: int, digest: int, moves: int, capacity: int, bytes: int) -> _Command: ...
    # Start background execution.
    def run(self) -> _Stream: ...

class _Stream:
    # Block until an event arrives or execution ends.
    def next(self) -> Optional[Event]: ...
    # Collect all remaining output.
    def collect_output(self) -> Output: ...
    # Cancel and release an idle stream.
    def close(self) -> None: ...
