[package]
name = "p4rust"
version = "0.1.3"
edition = "2024"
license = "MIT"
repository = "https://github.com/CatScarf/P4Rust"
description = "Safe Rust bindings to the official Perforce C++ client API"
readme = "README.md"
build = false

include = ["src/**", "/README.md", "/LICENSE", "/Cargo.toml"]

[workspace]
members = ["xtask", "resources/*"]
default-members = ["."]
resolver = "3"

[target.x86_64-pc-windows-msvc.dependencies]
p4rust-resources-x86_64-pc-windows-msvc = { version = "=0.1.3", path = "resources/x86_64-pc-windows-msvc" }

[target.aarch64-pc-windows-msvc.dependencies]
p4rust-resources-aarch64-pc-windows-msvc = { version = "=0.1.3", path = "resources/aarch64-pc-windows-msvc" }

[target.x86_64-unknown-linux-gnu.dependencies]
p4rust-resources-x86_64-unknown-linux-gnu = { version = "=0.1.3", path = "resources/x86_64-unknown-linux-gnu" }

[target.aarch64-unknown-linux-gnu.dependencies]
p4rust-resources-aarch64-unknown-linux-gnu = { version = "=0.1.3", path = "resources/aarch64-unknown-linux-gnu" }

[target.x86_64-apple-darwin.dependencies]
p4rust-resources-x86_64-apple-darwin = { version = "=0.1.3", path = "resources/x86_64-apple-darwin" }

[target.aarch64-apple-darwin.dependencies]
p4rust-resources-aarch64-apple-darwin = { version = "=0.1.3", path = "resources/aarch64-apple-darwin" }


[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
