[package]
name = "p4rust-resources-aarch64-unknown-linux-gnu"
version = "0.1.2"
edition = "2024"
license = "MIT AND BSD-2-Clause AND Apache-2.0"
description = "Precompiled Perforce C ABI resources for aarch64-unknown-linux-gnu"
repository = "https://github.com/CatScarf/P4Rust"
links = "p4rust_abi_v3_aarch64_unknown_linux_gnu"
include = ["src/**", "/build.rs", "native/**", "/LICENSE", "/NATIVE-INPUTS.sha256", "/PERFORCE-LICENSE.txt", "/OPENSSL-LICENSE.txt", "/Cargo.toml"]

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
